Dataflow pipeline
fprost/cloudml-samples pull request #1
Opened 2018-11-28 14:16 UTC by fprost

Creating the structure for the Dataflow script.

Our goal here is to add to estimator/ a template for a Dataflow job. The pipeline will be simple (just train/eval split) but it will be useful both for teaching purposes and for using it as a template for all Dataflow projects (typical structure).

2018-11-28 14:57 UTC, fprost commented
@happyhuman

2018-12-07 22:58 UTC, cfezequiel commented on census/estimator/preprocessing/preprocess.py
> +  def read_records(self, file_name, range_tracker):
`range_tracker` appears unused. You can rename it to `unused_range_tracker` if it's needed in the signature, or write the following in the function body:
```
_ = range_tracker
```

2018-12-07 22:58 UTC, cfezequiel commented on census/estimator/run_preprocessing.py
> +      '--project_name',
Minor nit: consider using `project_id` as it seems to be the common term used to refer to the Cloud project in documentation.

2018-12-11 20:26 UTC, cfezequiel approved these changes

2018-12-11 20:26 UTC, fprost commented
@gogasca @dizcology @thedriftofwords @happyhuman

Initial code review for the feature request [here](https://github.com/GoogleCloudPlatform/cloudml-samples/issues/315). We will write code in this fork, make small PRs here and merge with master when ready. 

Thank you

2018-12-18 17:49 UTC, gogasca requested changes

2018-12-18 17:49 UTC, gogasca commented on census/estimator/requirements.txt
> +tensorboard==1.9.0
Any reason why we use TB 1.9 vs 1.10 ?

2018-12-18 17:49 UTC, gogasca commented on census/estimator/requirements.txt
> +tensorflow==1.10.0
New runtime 1.12 will be available this week.

2018-12-18 17:49 UTC, gogasca commented on census/estimator/run_preprocessing.py
> +        # 'setup_file': os.path.abspath(os.path.join(
clean up this?

2018-12-18 17:49 UTC, gogasca commented on census/estimator/README.md
> +The current code uses the test set to control overfitting or to do hyper parameter tuning, while we typically recommend to use an evaluation set for this.
nit: hyper parameter -> hyperparameter

2018-12-18 17:49 UTC, gogasca commented on census/estimator/bin/run.preprocess.sh
> +DATAFLOW_DIR=gs://census-example/preprocessing/${JOB_NAME}
Maybe use a place holder for people to choose their own BUCKET_NAME or an argument?:
```
BUCKETNAME='census-example'
DATAFLOW_DIR=gs://$BUCKETNAME/preprocessing/${JOB_NAME}
```

2018-12-18 21:41 UTC, fprost commented on census/estimator/requirements.txt
> +tensorboard==1.9.0
Modified to 1.10

2018-12-18 21:41 UTC, fprost commented on census/estimator/requirements.txt
> +tensorflow==1.10.0
Good to know. Will update this when available

2018-12-18 21:41 UTC, fprost commented on census/estimator/run_preprocessing.py
> +        # 'setup_file': os.path.abspath(os.path.join(
done

2018-12-18 21:41 UTC, fprost commented on census/estimator/README.md
> +The current code uses the test set to control overfitting or to do hyper parameter tuning, while we typically recommend to use an evaluation set for this.
done

2018-12-18 21:43 UTC, fprost commented on census/estimator/bin/run.preprocess.sh
> +DATAFLOW_DIR=gs://census-example/preprocessing/${JOB_NAME}
done.

2018-12-18 21:57 UTC, gogasca approved these changes
LGTM

2018-12-19 13:06 UTC, merged